name       : mutt
version    : 2.2.5
release    : 30
source     :
    - https://gitlab.com/muttmua/mutt/-/archive/mutt-2-2-5-rel/mutt-mutt-2-2-5-rel.tar.bz2 : 3afe52dd2ae60007cd1136dfbd9ba2f5314d338b48195655061936a5032ec506
homepage   : http://www.mutt.org
license    : GPL-2.0-or-later
component  : network.mail
summary    : Mutt (Small, powerful text based email client)
description: |
    Mutt is a small but powerful text-based mail client for Unix operating systems. It was originally based on ELM, and was written by Michael Elkins.
builddeps  :
    - pkgconfig(gpgme)
    - pkgconfig(libassuan)
    - pkgconfig(libsasl2)
    - pkgconfig(ncursesw)
    - gdbm-devel
    - gnupg
rundeps    :
    - vim
setup      : |
    %reconfigure \
        --sysconfdir=/etc/mutt \
        --enable-compressed \
        --enable-gpgme \
        --enable-hcache \
        --enable-imap \
        --enable-locales-fix \
        --enable-pop \
        --enable-sidebar \
        --enable-smtp \
        --with-curses \
        --with-homespool=/var/spool/ \
        --with-regex \
        --with-sasl \
        --with-ssl
build      : |
    %make
install    : |
    %make_install
