name        : mutt
version     : 1.5.24
release     : 4
source      :
    - https://bitbucket.org/mutt/mutt/downloads/mutt-1.5.24.tar.gz : a292ca765ed7b19db4ac495938a3ef808a16193b7d623d65562bb8feb2b42200
homepage    : http://www.mutt.org
license     : GPL-2.0
summary     : Mutt (Small, powerful text based email client)
description : |
    Mutt is a small but powerful text-based mail client for Unix operating systems. It was originally based on ELM, and was written by Michael Elkins.
builddeps   :
    - pkgconfig(ncursesw)
    - gnupg
    - gpgme-devel
    - libassuan-devel
rundeps     :
    - vim
setup      : |
    %configure --sysconfdir=/etc/mutt \
               --enable-pop \
               --enable-imap \
               --enable-smtp \
               --enable-gpgme \
               --enable-locales-fix \
               --enable-hcache \
               --with-curses \
               --with-regex \
               --with-ssl \
               --with-homespool=/var/spool/
build      : |
    %make
install    : |
    %make_install
    ln -s /usr/bin/vim /usr/bin/vi
