name       : mutt
version    : 1.14.5
release    : 25
source     :
    - https://gitlab.com/muttmua/mutt/-/archive/mutt-1-14-5-rel/mutt-mutt-1-14-5-rel.tar.bz2 : d8e919a65516baa638e7208a5d57326f40715548b2d088c2a4b9026df21af637
license    : GPL-2.0-or-later
component  : network.mail
summary    : Mutt (Small, powerful text based email client)
description: |
    Mutt is a small but powerful text-based mail client for Unix operating systems. It was originally based on ELM, and was written by Michael Elkins.
builddeps  :
    - pkgconfig(gpgme)
    - pkgconfig(libassuan)
    - pkgconfig(libsasl2)
    - pkgconfig(ncursesw)
    - gdbm-devel
    - gnupg
rundeps    :
    - vim
setup      : |
    %reconfigure --sysconfdir=/etc/mutt \
               --enable-compressed \
               --enable-gpgme \
               --enable-hcache \
               --enable-imap \
               --enable-locales-fix \
               --enable-pop \
               --enable-sidebar \
               --enable-smtp \
               --with-curses \
               --with-homespool=/var/spool/ \
               --with-regex \
               --with-sasl \
               --with-ssl
build      : |
    %make
install    : |
    %make_install
