name       : mutt
version    : 1.6.2
release    : 7
source     :
    - https://bitbucket.org/mutt/mutt/downloads/mutt-1.6.2.tar.gz : c5d02ef06486cdf04f9eeb9e9d7994890d8dfa7f47e7bfeb53a2a67da2ac1d8e
license    : GPL-2.0
component  : network.mail
summary    : Mutt (Small, powerful text based email client)
description: |
    Mutt is a small but powerful text-based mail client for Unix operating systems. It was originally based on ELM, and was written by Michael Elkins.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(ncursesw)
    - gnupg
    - gpgme-devel
    - libassuan-devel
rundeps    :
    - vim
setup      : |
    %configure --sysconfdir=/etc/mutt \
               --enable-pop \
               --enable-imap \
               --enable-smtp \
               --enable-gpgme \
               --enable-locales-fix \
               --enable-hcache \
               --with-curses \
               --with-regex \
               --with-ssl \
               --with-sasl \
               --with-homespool=/var/spool/
build      : |
    %make
install    : |
    %make_install
    ln -s /usr/bin/vim /usr/bin/vi
