name        : mutt
version     : 1.5.23
release     : 2
source      :
    - https://bitbucket.org/mutt/mutt/downloads/mutt-1.5.23.tar.gz : 3af0701e57b9e1880ed3a0dee34498a228939e854a16cdccd24e5e502626fd37
homepage    : http://www.mutt.org
license     : GPL-2.0
summary     : Mutt (Small, powerful text based email client)
rundeps     :
    - vim
builddeps   :
    - ncurses-devel
    - gpgme-devel
    - gnupg
    - libassuan-devel
description : |
    Mutt is a small but powerful text-based mail client for Unix operating systems. It was originally based on ELM, and was written by Michael Elkins.
setup      : |
    %configure --sysconfdir=/etc/mutt \
               --enable-pop \
               --enable-imap \
               --enable-smtp \
               --enable-gpgme \
               --enable-locales-fix \
               --enable-hcache \
               --with-curses \
               --with-regex \
               --with-homespool=$HOME/mbox \
               --with-ssl
build      : |
    %make
install    : |
    %make_install
    ln -s /usr/bin/vim /usr/bin/vi
