name       : mutt
version    : 1.9.1
release    : 13
source     :
    - http://ftp.mutt.org/pub/mutt/mutt-1.9.1.tar.gz : 749b83a96373c6e2101ebe8c4b9a651735e02c478edb750750a5146a15d91bb1
license    : GPL-2.0
component  : network.mail
summary    : Mutt (Small, powerful text based email client)
description: |
    Mutt is a small but powerful text-based mail client for Unix operating systems. It was originally based on ELM, and was written by Michael Elkins.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(ncursesw)
    - gdbm-devel
    - gnupg
    - gpgme-devel
    - libassuan-devel
rundeps    :
    - vim
setup      : |
    %configure --sysconfdir=/etc/mutt \
               --enable-compressed \
               --enable-gpgme \
               --enable-hcache \
               --enable-imap \
               --enable-locales-fix \
               --enable-pop \
               --enable-sidebar \
               --enable-smtp \
               --with-curses \
               --with-homespool=/var/spool/ \
               --with-regex \
               --with-sasl \
               --with-ssl
build      : |
    %make
install    : |
    %make_install
